# yaml-language-server: $schema=https://raw.githubusercontent.com/JanDeDobbeleer/oh-my-posh/main/themes/schema.json

palette:
    blue: '#89B4FA'
    lavender: '#B4BEFE'
    os: '#ACB0BE'
    pink: '#F5C2E7'
    text: '#1E1E2E'
    wight: '#CDD6F4'
secondary_prompt:
    template: '<p:blue,transparent></><,p:blue> > </><p:blue,transparent></> '
    foreground: p:text
    background: transparent
transient_prompt:
    template: '<p:blue,transparent></><,p:blue></><p:blue,transparent></> '
    foreground: p:wight
    background: transparent
upgrade:
    source: cdn
    interval: 168h
    auto: false
    notice: false
blocks:
    - type: prompt
      alignment: left
      segments:
        - leading_diamond: 
          template: '{{.Icon}} '
          foreground: p:wight
          powerline_symbol: 
          background: p:blue
          type: os
          style: diamond
        - template: '{{ .UserName }}@{{ .HostName }}'
          foreground: p:text
          powerline_symbol: 
          background: p:blue
          type: session
          style: diamond
        - properties:
            folder_icon: ....
            home_icon: "~"
            style: agnoster_short
          template: ' {{ .Path }}'
          foreground: p:text
          powerline_symbol: 
          background: p:pink
          type: path
          style: powerline
        - properties:
            branch_icon: ' '
            cherry_pick_icon: ' '
            commit_icon: ' '
            fetch_status: false
            fetch_upstream_icon: false
            merge_icon: ' '
            no_commits_icon: ' '
            rebase_icon: ' '
            revert_icon: ' '
            tag_icon: ' '
          template: ' {{ .HEAD }}'
          foreground: p:text
          powerline_symbol: 
          background: p:lavender
          type: git
          style: powerline
          newline: true
block:
  alignment: right
  overflow: hide
  filler: "{{ if gt .Code 0 }}{{ else }}{{ end }}"
#ztransient_prompt:
 # template: '<p:blue,transparent><p:blue,transparent>{{ .Shell }}<,p:blue><,p:blue> '
  #foreground: 'p:blue'
  #background: transparent
version: 3
final_space: true
