version = 3
final_space = true

[palette]
  blue = '#89B4FA'
  lavender = '#B4BEFE'
  os = '#ACB0BE'
  pink = '#F5C2E7'
  text = '#1E1E2E'
  wight = '#CDD6F4'
  red = '#f38ba8'
  green = '#A6E3A1'

[secondary_prompt]
  template = '<p:blue,transparent></><,p:blue> > </><p:blue,transparent></> '
  foreground = 'p:text'
  background = 'transparent'

[transient_prompt]
  template = '<p:blue,transparent></><,p:blue></><p:blue,transparent></> '
  foreground = 'p:wight'
  background = 'transparent'

[upgrade]
  source = 'cdn'
  interval = '168h'
  auto = false
  notice = false

[[blocks]]
  type = 'prompt'
  alignment = 'left'

  [[blocks.segments]]
    leading_diamond = ''
    template = '{{.Icon}} '
    foreground = 'p:wight'
    powerline_symbol = ''
    background = 'p:blue'
    type = 'os'
    style = 'diamond'

  [[blocks.segments]]
    template = '{{ .UserName }}@{{ .HostName }}'
    foreground = 'p:text'
    powerline_symbol = ''
    background = 'p:blue'
    type = 'session'
    style = 'diamond'

  [[blocks.segments]]
    template = ' {{ .Path }}'
    foreground = 'p:text'
    powerline_symbol = ''
    background = 'p:pink'
    type = 'path'
    style = 'powerline'

    [blocks.segments.properties]
      folder_icon = '....'
      home_icon = '~'
      style = 'agnoster_short'

  [[blocks.segments]]
    template = ' {{ .HEAD }}'
    foreground = 'p:text'
    powerline_symbol = ''
    background = 'p:lavender'
    type = 'git'
    style = 'powerline'
    newline = true

    [blocks.segments.properties]
      branch_icon = ' '
      cherry_pick_icon = ' '
      commit_icon = ' '
      fetch_status = false
      fetch_upstream_icon = false
      merge_icon = ' '
      no_commits_icon = ' '
      rebase_icon = ' '
      revert_icon = ' '
      tag_icon = ' '
  [[blocks.segments]]
    template = ' {{ .Code }}'
    type = 'text'
    style = 'powerline'
    background_templates = [
      "{{if gt .Code 0}}p:red{{end}}",
      "{{if eq .Code 0}}p:green{{end}}",
    ]
    foreground = 'p:text'
    powerline_symbol = ''

